# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: https://github.com/actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: 0


    - name: Set up Go
      uses: https://github.com/actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: build
      run: make

    - name: build-systray
      run: make SYSTRAY=true

    - name: test
      run: make ci-test
